### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dragonwocky** [BoxOfDevs/BoxManager#2]
Here are the features we need to add for what BoxM basically does:
- [x] Login & Registration System
- [x] Users can submit a resource but it will not be shown public until a "Resource Reviewer" approves it
- [x] A rating system
- [ ] A comment system
- [x] Configurable resource categorys (ex: Standalone, Plugins, Website, Apps)
- [10%] An Admin CP with Ability to set users who are "Resource Reviewers"
- [50%] Resource images and user avatars
- [x] A download count system
- [ ] Update system
- [ ] In Admin CP you can set a site icon (will become the favicon.png)
- [67%] A nice theme and user interface (#13)
- [50%] Bug fixings (#12)

Not a need to be for 1.0 but can be nice additions:
- [20%] An API with some features to create addons (custom styling, resource handling ...).
- [ ] Tags (ex: Experimental, Stable, Incomplete, Abandoned, Complete, Outdated, Dev, Beta)
- [50%] In Admin CP there is an option where you can choose it to be an organisation-based or public-based resource submission.
- [ ] Featuring system
- [ ] Markdown support

When you add these things, do not make them site specific to http://boxofdevs.com - This software is for ANYONE to download and use, so keep logo's and titles etc configurable!
If you come up with any other things just comment here and I'll add to list!

**Comment by dragonwocky** [comment]
Btw change the copyright at the bottom from
(C) 2016 BoxManager - BoxOfDevs team.
To
Powered by BoxManager - Copyright (C) BoxOfDevs Team 2016
Not sure how to do that......

**Comment by Vaults1** [comment]
Ok

**Comment by Ad5001** [comment]
Powered by BoxManager by (c) BoxOfDevs Team, 2016

**Comment by Ad5001** [comment]
Hmmm
@UltimateMcraft Do you wanna start the resource reviewer system with me? Like yo manag to set who is which plugin reviewer (might help you in the admin CP) and by starting of this, I will do the approvement system....

**Comment by Ad5001** [comment]
By waiting your answer, I will do the category system.

**Comment by Ad5001** [comment]
I kinda don't understand what do you mean by moving the website... Why don't they just move the folder :S ?

**Comment by Vaults1** [comment]
If they change the location of the software, it should not break.

**Comment by Ad5001** [comment]
Yeah so what's the point of doing this... It will just eat place in the soft for almost nothing...

But I had an another idea. Why not making an auto updater?

**Comment by Vaults1** [comment]
Good idea. How will we make it check releases? I'm using github releases.

**Comment by Ad5001** [comment]
We can just host something on the BOD website basicly broadcasting the last BodM version then software check it's version, if the version is superior, say that there is an update !

**Comment by Vaults1** [comment]
Oh yes. :P Will we use the mc-pe.game domain or should we make a BoxManager website?

 If we use the mc-pe.ga domain, can you send the FTP login?

**Comment by Ad5001** [comment]
@TheDragonRing didn't even give us any access to boxofdevs.com so.... I  will use mc-pe.ga and create you an FTP account (if I can) :)

**Comment by Ad5001** [comment]
Yup created an account will pm you the creditentials on twitter ;)
EDIT: If my connection is good enought to connect to your twitter profile :'(
EDIT2: Done :)

**Comment by Ad5001** [comment]
Yup created an account will pm you the creditentials on twitter ;)

**Comment by Ad5001** [comment]
BTW my testing URL changed: http://projects.ad5001.eu/BoxManager

**Comment by dragonwocky** [comment]
Well, it's still nowhere near done... But I think you know what your doing (I certainly don't! :P).

Also sorry about not giving website access... I'll do that now (check forums chat).

**Comment by Ad5001** [comment]
I one more time modified your first message @TheDragonRing. Look at it for more infos about what we'll be doing.
